# Generated by Django 2.2.4 on 2020-05-16 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cencal', '0002_auto_20200505_1538'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='author',
            field=models.TextField(default='centraldogma99', verbose_name='author'),
            preserve_default=False,
        ),
    ]
